# Generated by Django 4.0 on 2022-09-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('stopwords', models.TextField(blank=True, default='')),
                ('num_topics', models.IntegerField(null=True, verbose_name='n-Topic')),
                ('passes', models.IntegerField(null=True)),
                ('lda_data', models.TextField(blank=True, default='')),
                ('lda_terms', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=255)),
                ('hypernym_json', models.TextField(blank=True, max_length=255, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfo.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('wordnet', 'wordnet'), ('wiki', 'wiki'), ('tabel', 'tabel')], max_length=50)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('judge_username', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('continue_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfo.dataset')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'food categories',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_clean', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('definition_id', models.TextField(blank=True, null=True)),
                ('definition_ms', models.TextField(blank=True, null=True)),
                ('definition_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfo.dataset')),
                ('generated_categories', models.ManyToManyField(related_name='generated_categories', related_query_name='generated_category', to='nfo.FoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfo.dataset')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='WordnetAnswer',
            fields=[
                ('answermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfo.answermixin')),
                ('correct_hypernym', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfo.word')),
            ],
            bases=('nfo.answermixin',),
        ),
        migrations.CreateModel(
            name='WikiAnswer',
            fields=[
                ('answermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfo.answermixin')),
                ('suggested_categories', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfo.document')),
            ],
            bases=('nfo.answermixin',),
        ),
        migrations.CreateModel(
            name='TabelAnswer',
            fields=[
                ('answermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfo.answermixin')),
                ('suggested_categories', models.TextField(blank=True, null=True)),
                ('correct_categories', models.ManyToManyField(blank=True, related_name='correct_categories', related_query_name='correct_category', to='nfo.FoodCategory')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfo.document')),
            ],
            bases=('nfo.answermixin',),
        ),
    ]
