# Generated by Django 4.0 on 2023-07-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='raw_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='generated_categories',
            field=models.ManyToManyField(blank=True, related_name='generated_categories', related_query_name='generated_category', to='nfo.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='tabelanswer',
            name='correct_categories',
            field=models.ManyToManyField(blank=True, related_name='tabel_answer', related_query_name='tabel_answer', to='nfo.FoodCategory'),
        ),
        migrations.CreateModel(
            name='WordnetAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=255)),
                ('judge_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfo.judgesession')),
            ],
        ),
        migrations.CreateModel(
            name='TabelAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=255)),
                ('judge_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfo.judgesession')),
            ],
        ),
    ]
